# Generated by Django 5.2 on 2025-05-04 05:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 4, 5, 32, 36, 309723, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
