# Generated by Django 5.2 on 2025-05-04 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 4, 5, 40, 54, 332922, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
