# Generated by Django 5.2 on 2025-05-04 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_project_pub_date_scoreaggregation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 4, 11, 32, 45, 922649, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
