# Generated by Django 5.2 on 2025-05-04 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_project_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 4, 11, 54, 24, 456328, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='scoreaggregation',
            name='average_scores',
            field=models.FloatField(default=0),
        ),
    ]
